export const SUCCESS_NOTIFICATION_DEFAULT_TIMER_IN_MILISSECONDS = 5000;

export const ERROR_NOTIFICATION_DEFAULT_TIMER_IN_MILISSECONDS = 10000;

export const WARN_NOTIFICATION_DEFAULT_TIMER_IN_MILISSECONDS = 8000;
